### ISSUE TITLE
Adding two favs with the same name adds both. Deleting one removes both

### ISSUE THREAD

**Issue by ovichiro** [raguay/favorites#10]
My expectation would be for a new favorite with the same name to overwrite the old one. Otherwise the behavior should be consistent with deleting.

**Comment by raguay** [comment]
Yes, I'm just adding without checking for one already. Deleting removes all
with the same name. When I have time, I'll add checking for existing.
Thanks.

Richard

**Comment by raguay** [comment]
Okay. It no longer creates duplicates. Sorry it took a while. I've been very busy.
