### ISSUE TITLE
Adding a network folder causes issues with the address

### ISSUE THREAD

**Issue by aguirreeng** [raguay/favorites#8]
I have added a network path as a favorite, e.g. `\\fileserver\public` when I use the shortcut to go to this folder, the address that is shown is `C:\Users\user\AppData\Local\fman\Versions\1.4.4\network:\fileserver\public`. From this point, any operation I try to perform fails (as expected).

**Comment by raguay** [comment]
I'm sorry, I did not see this post before now.

I can't reproduce this since all of my windows systems are currently dead. I have a vm of XP, but I'm having a hard time getting it to connect to a network drive for testing. But, I do have issues with other alternate file systems. I'll keep checking, but I have very limited time.

Sorry for the inconvenience.

**Comment by Akamaozu** [comment]
@aguirreeng I have a Windows machine. Maybe I can help.

Can you give me step my step instructions on adding a network drive?

I can follow, replicate and debug if any issues come up.

**Comment by aguirreeng** [comment]
Hi @Akamaozu and @raguay,  

@Akamaozu: What I have done was just navigated to a network folder (on a Windows network). To do it I have used `CTRL+P` to open the navigation panel and entered the network path (`\\fileserver\public`). Then I have just followed the instructions to add this folder as a favorite (using `SHIFT+f`). When trying to move back to the folder later (using `CTRL+0`) I had the issue I have mentioned.

Thank you for your help!

@raguay: I will also try to take a look at the plugin code to try to understand what is the issue.

Cheers.

**Comment by raguay** [comment]
I found an article on mapping a drive on windows 10:  https://www.groovypost.com/howto/map-network-drive-windows-10/

This should work the same as the "c:/" type drives except for the higher letter. But, the above note is showing a network drive that isn't mounted. If your intent is to have a non-mounted network drive, the fman API for setting the directory will not work. It needs to be a mounted drive first. I should of noticed this at first.

Try mounting the drive first and then saving it as a favorite. It would need to be remounted as the same drive each time you try to go to it as a favorite. You can set the mount to automatically remount on each boot.

Let me know if this helps. Also, you can post your `~/.favoritedirs` file here to see what fman is saving as the directory.
